Description: Vote Processor
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Name of the stage
  tablename:
    Type: String
    Default: tpm-2449
    Description: Name of the Dynamo DB Table

Globals:
  Function:
    Runtime: nodejs14.x
    Tracing: Active

Resources:
  IAMLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: allowLambdaLogs-tpm2449
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:*
              Resource: arn:aws:logs:*:*:*
        - PolicyName: allowDynamoDB-tpm2449
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource:
                - arn:aws:dynamodb:us-east-1:162174280605:table/tpm-2449
        - PolicyName: allowDynamoDBStream-tpm2449
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource:
                - arn:aws:dynamodb:us-east-1:162174280605:table/tpm-2449/stream/2022-03-23T08:23:07.321
  VoteLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: VoteLambda-tpmspec2449
      PackageType: Zip
      Runtime: nodejs14.x
      CodeUri: ./build/
      Handler: vote.handler
      Role: !GetAtt 
        - IAMLambdaRole
        - Arn
      Events:
        APIEvent:
          Type: HttpApi 
          Properties:
            Path: /vote
            Method: post
      Environment:
        Variables:
          VOTING_TABLE: !Ref tablename
  StreamLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AggregateLambda-tpmspec2449
      PackageType: Zip
      Runtime: nodejs14.x
      CodeUri: ./build/
      Handler: aggregate.handler
      Role: !GetAtt 
        - IAMLambdaRole
        - Arn
      Events:
        StreamEvent:
          Type: DynamoDB 
          Properties:
            Stream: arn:aws:dynamodb:us-east-1:162174280605:table/tpm-2449/stream/2022-03-23T08:23:07.321
            StartingPosition: LATEST
      Environment:
        Variables:
          VOTING_TABLE: !Ref tablename
  ResultLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ResultLambda-tpmspec2449
      PackageType: Zip
      Runtime: nodejs14.x
      CodeUri: ./build/
      Handler: result.handler
      Role: !GetAtt 
        - IAMLambdaRole
        - Arn
      Events:
        APIEvent:
          Type: HttpApi 
          Properties:
            Path: /result
            Method: get
      Environment:
        Variables:
          VOTING_TABLE: !Ref tablename

Outputs:
  Stack:
    Description: CloudFormation Stack URL
    Value: !Sub "https://console.aws.amazon.com/cloudformation/home?region=${AWS::Region}#/stacks/resources?stackId=${AWS::StackId}&filteringStatus=active&filteringText=&viewNested=true&hideStacks=false"